services:
  dev-db:
    image: pgvector/pgvector:pg15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nest-network
      
       
  test-db:
    image: pgvector/pgvector:pg15
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nest-network 
networks:
  nest-network:
